#!/bin/bash
# =============================================================================
# nepal_decarb_pro — one-command VPS deployment
# =============================================================================
# Provisions a $20/month VPS (DigitalOcean/Hetzner/any Ubuntu 22.04) with
# the full nepal_decarb_pro stack: FastAPI + Streamlit + MQTT + Postgres.
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/himalayan-carbon-nepal/nepal_decarb_pro/main/deploy/vps/deploy.sh | sudo bash
#   # or locally:
#   sudo ./deploy.sh
#
# Tested on: Ubuntu 22.04 LTS, 4GB RAM, 2 vCPU ($20/mo Hetzner CX21)
# =============================================================================
set -euo pipefail

APP_USER="nepaldec"
APP_DIR="/opt/nepal_decarb_pro"
DOMAIN="${DOMAIN:-nepalcarbon.local}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@example.com}"
DB_PASSWORD="${DB_PASSWORD:-$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)}"
JWT_SECRET="${JWT_SECRET:-$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)}"
MQTT_PASSWORD="${MQTT_PASSWORD:-$(openssl rand -base64 16 | tr -d '/+=' | head -c 16)}"
GIT_REPO="${GIT_REPO:-https://github.com/himalayan-carbon-nepal/nepal_decarb_pro.git}"
GIT_BRANCH="${GIT_BRANCH:-main}"

# ---- Colors ----
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()  { echo -e "${RED}[ERR ]${NC} $1"; }

# ---- Sanity ----
if [ "$EUID" -ne 0 ]; then
  err "Please run as root: sudo $0"
  exit 1
fi

if [ ! -f /etc/os-release ] || ! grep -q "ubuntu\|debian" /etc/os-release; then
  warn "Tested on Ubuntu 22.04. Continuing anyway."
fi

info "Starting deployment of nepal_decarb_pro v1.0.1"
info "Domain: $DOMAIN"
info "DB password generated (saved to /root/.nepal_decarb.env)"

# ---- Install Docker ----
if ! command -v docker &> /dev/null; then
  info "Installing Docker..."
  curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
  sh /tmp/get-docker.sh
  systemctl enable docker
  systemctl start docker
else
  info "Docker already installed: $(docker --version)"
fi

if ! command -v docker compose &> /dev/null; then
  warn "docker compose plugin not found. Installing..."
  apt-get update -qq
  apt-get install -y -qq docker-compose-plugin
fi

# ---- Create app user ----
if ! id "$APP_USER" &> /dev/null; then
  info "Creating app user $APP_USER"
  useradd -r -m -s /bin/bash "$APP_USER"
  usermod -aG docker "$APP_USER"
fi

# ---- Clone or update repo ----
if [ -d "$APP_DIR/.git" ]; then
  info "Updating existing repo at $APP_DIR"
  cd "$APP_DIR"
  sudo -u "$APP_USER" git fetch --all
  sudo -u "$APP_USER" git checkout "$GIT_BRANCH"
  sudo -u "$APP_USER" git pull --rebase --autostash
else
  info "Cloning $GIT_REPO to $APP_DIR"
  git clone --branch "$GIT_BRANCH" "$GIT_REPO" "$APP_DIR"
  chown -R "$APP_USER:$APP_USER" "$APP_DIR"
fi

cd "$APP_DIR"

# ---- Create .env ----
info "Writing /opt/nepal_decarb_pro/.env"
cat > "$APP_DIR/.env" <<EOF
# Auto-generated by deploy.sh on $(date)
DOMAIN=$DOMAIN
ADMIN_EMAIL=$ADMIN_EMAIL
POSTGRES_PASSWORD=$DB_PASSWORD
JWT_SECRET=$JWT_SECRET
MQTT_PASSWORD=$MQTT_PASSWORD
ENVIRONMENT=production
TZ=Asia/Kathmandu
LOG_LEVEL=INFO
# Set to 1 to enable the LLM advisor (requires GPU + model weights)
ENABLE_LLM_ADVISOR=0
# Set to your email or Slack webhook for alerts
ALERT_WEBHOOK=
EOF
chmod 600 "$APP_DIR/.env"
chown "$APP_USER:$APP_USER" "$APP_DIR/.env"

# ---- Save credentials ----
cat > /root/.nepal_decarb.env <<EOF
# DO NOT COMMIT THIS FILE
DOMAIN=$DOMAIN
DB_PASSWORD=$DB_PASSWORD
JWT_SECRET=$JWT_SECRET
MQTT_PASSWORD=$MQTT_PASSWORD
EOF
chmod 600 /root/.nepal_decarb.env

# ---- Run database migrations ----
info "Starting database..."
cd "$APP_DIR/deploy/vps"
docker compose --env-file "$APP_DIR/.env" up -d db
sleep 8
info "Waiting for database to be ready..."
for i in {1..30}; do
  if docker exec nepal-decarb-db pg_isready -U nepal_admin -d nepal_decarb &> /dev/null; then
    info "Database is ready"
    break
  fi
  sleep 2
done

# ---- Start full stack ----
info "Starting full stack..."
docker compose --env-file "$APP_DIR/.env" up -d

# ---- Wait for services ----
info "Waiting for services to come up..."
sleep 15
for i in {1..30}; do
  if curl -fsS http://localhost:8000/health &> /dev/null; then
    info "FastAPI is up"
    break
  fi
  sleep 2
done
for i in {1..30}; do
  if curl -fsS http://localhost:8501/_stcore/health &> /dev/null; then
    info "Streamlit is up"
    break
  fi
  sleep 2
done

# ---- Create admin user ----
info "Creating admin user..."
docker exec nepal-decarb-api python -c "
import sys
sys.path.insert(0, '/app')
from nepal_decarb_pro.auth.service import create_user
try:
    create_user(email='$ADMIN_EMAIL', password='$DB_PASSWORD', role='admin', tenant_id='default')
    print('Admin user created: $ADMIN_EMAIL')
except Exception as e:
    print(f'Admin user may already exist: {e}')
" || warn "Could not create admin user automatically; do it via UI"

# ---- Setup nginx + SSL ----
if [ "$DOMAIN" != "nepalcarbon.local" ]; then
  info "Setting up nginx + Let's Encrypt for $DOMAIN"
  apt-get install -y -qq nginx certbot python3-certbot-nginx
  cat > /etc/nginx/sites-available/nepal-decarb <<EOF
server {
    listen 80;
    server_name $DOMAIN www.$DOMAIN;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /ui/ {
        proxy_pass http://127.0.0.1:8501/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }

    location /mqtt/ {
        proxy_pass http://127.0.0.1:1883/;
        proxy_set_header Host \$host;
        proxy_http_version 1.1;
    }
}
EOF
  ln -sf /etc/nginx/sites-available/nepal-decarb /etc/nginx/sites-enabled/
  rm -f /etc/nginx/sites-enabled/default
  nginx -t && systemctl reload nginx
  certbot --nginx --non-interactive --agree-tos -m "$ADMIN_EMAIL" -d "$DOMAIN" || \
    warn "SSL setup failed. Set up certbot manually: certbot --nginx -d $DOMAIN"
else
  warn "Skipping SSL setup (DOMAIN is localhost)"
fi

# ---- Setup backup cron ----
info "Setting up daily backup cron..."
cat > /etc/cron.daily/nepal-decarb-backup <<EOF
#!/bin/bash
# Daily backup of nepal_decarb_pro database
set -e
BACKUP_DIR=/var/backups/nepal-decarb
mkdir -p \$BACKUP_DIR
TIMESTAMP=\$(date +%Y%m%d-%H%M%S)
docker exec nepal-decarb-db pg_dump -U nepal_admin -d nepal_decarb | gzip > \$BACKUP_DIR/db-\$TIMESTAMP.sql.gz
# Retain last 30 daily backups
find \$BACKUP_DIR -name "db-*.sql.gz" -mtime +30 -delete
echo "Backup completed: \$BACKUP_DIR/db-\$TIMESTAMP.sql.gz" >> /var/log/nepal-decarb-backup.log
EOF
chmod +x /etc/cron.daily/nepal-decarb-backup
info "Daily backup installed at /etc/cron.daily/nepal-decarb-backup"

# ---- Setup logrotate ----
cat > /etc/logrotate.d/nepal-decarb <<EOF
/var/log/nepal-decarb/*.log {
    daily
    rotate 30
    compress
    missingok
    notifempty
    create 0640 root root
}
EOF

# ---- Setup firewall ----
info "Configuring UFW firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 1883/tcp comment "MQTT (consider restricting)"
ufw --force enable

# ---- Print summary ----
PUBLIC_IP=$(curl -fsS http://checkip.amazonaws.com || echo "<your-server-ip>")
info "============================================="
info " DEPLOYMENT COMPLETE"
info "============================================="
info " FastAPI:    http://$PUBLIC_IP:8000/docs"
info " Streamlit:  http://$PUBLIC_IP:8501"
info " MQTT:       mqtt://$PUBLIC_IP:1883  (user: nepal, pass from /root/.nepal_decarb.env)"
info " Admin user: $ADMIN_EMAIL"
info " DB password: /root/.nepal_decarb.env"
info "============================================="
info " Next steps:"
info "   1. Point your domain ($DOMAIN) to $PUBLIC_IP"
info "   2. Re-run with DOMAIN=yourdomain.com to enable SSL"
info "   3. Open the UI and create your first plant tenant"
info "   4. Onboard plants: docs/PLANT_ONBOARDING.md"
info "============================================="
