"""
I/O for kiln simulation results.

Supports CSV (per-time, per-zone trajectories), JSON (engineered outputs),
pickle (full state for re-loading), and emits MATLAB / Octave scripts that
re-implement the same model in those languages for cross-validation.
"""
from __future__ import annotations

import json
import os
import pickle
from pathlib import Path
from typing import Any, Dict, Optional

import numpy as np

from .kiln_ode import KilnParameters, KilnState


def save_results_csv(path: str, t: np.ndarray, y: np.ndarray,
                     x: np.ndarray, p: KilnParameters) -> str:
    """Save full trajectory as a wide-format CSV.

    Columns: time_s, x_m, T_solid_K, T_gas_K, T_wall_K, conversion, CO2, O2
    """
    n = p.n_zones
    rows = []
    header = ["time_s", "x_m", "T_solid_K", "T_gas_K", "T_wall_K",
              "conversion", "CO2", "O2"]
    for ti in range(len(t)):
        for zi in range(n):
            rows.append([
                float(t[ti]),
                float(x[zi]),
                float(y[6 * zi + 0, ti]),
                float(y[6 * zi + 1, ti]),
                float(y[6 * zi + 2, ti]),
                float(y[6 * zi + 3, ti]),
                float(y[6 * zi + 4, ti]),
                float(y[6 * zi + 5, ti]),
            ])
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(",".join(header) + "\n")
        for r in rows:
            f.write(",".join(f"{v:.6g}" for v in r) + "\n")
    return path


def load_results_csv(path: str) -> Dict[str, np.ndarray]:
    """Load a CSV produced by save_results_csv. Returns column dict."""
    import csv
    cols: Dict[str, list] = {}
    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            for k, v in row.items():
                cols.setdefault(k, []).append(float(v))
    return {k: np.array(v) for k, v in cols.items()}


def save_results_json(path: str, state: KilnState, p: KilnParameters,
                      outputs: Dict[str, float]) -> str:
    """Save engineered outputs as JSON (for dashboards, MRV)."""
    payload = {
        "tool": "nepal_kiln_sim",
        "version": "0.2.0",
        "parameters": json.loads(p.model_dump_json()),
        "state_summary": state.summary(),
        "outputs": outputs,
    }
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, default=_json_default)
    return path


def _json_default(o: Any) -> Any:
    if isinstance(o, np.ndarray):
        return o.tolist()
    if isinstance(o, (np.floating,)):
        return float(o)
    if isinstance(o, (np.integer,)):
        return int(o)
    if isinstance(o, (np.bool_,)):
        return bool(o)
    return str(o)


def save_state_pickle(path: str, state: KilnState, t: np.ndarray,
                      y: np.ndarray, p: KilnParameters) -> str:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as f:
        pickle.dump({"state": state, "t": t, "y": y, "p": p}, f)
    return path


def load_state_pickle(path: str) -> Dict[str, Any]:
    with open(path, "rb") as f:
        return pickle.load(f)


# -----------------------------------------------------------------------
# MATLAB / Octave script generation
# -----------------------------------------------------------------------

_MATLAB_TEMPLATE = """% {title}
% Generated by nepal_kiln_sim v{version} on {date}
% Run with MATLAB R2020b+ or GNU Octave 7+
%
% Solves the 5-zone rotary cement kiln ODE with parameters:
{params_block}

clear; clc;
n = {n_zones};
L = {length_m};
D = {diameter_m};
fuel_rate_t_h = {fuel_rate_t_h};
raw_meal_t_h = {raw_meal_throughput_t_h};
% ... see kiln_ode.m for the full set of parameters
tspan = [0 {t_end_s}];

% Initial state
y0 = zeros(6*n, 1);
for i = 1:n
    y0(6*i-5) = {T_s0};   % T_solid
    y0(6*i-4) = {T_g0};   % T_gas
    y0(6*i-3) = {T_w0};   % T_wall
    y0(6*i-2) = {conv0};  % conversion
    y0(6*i-1) = {co20};   % CO2
    y0(6*i-0) = {o20};    % O2
end

% Integrate with Radau (stiff)
options = odeset('RelTol', 1e-6, 'AbsTol', 1e-8, 'MaxStep', 10);
[t, y] = ode15s(@(t,y) kiln_rhs(t, y, n, L, D, fuel_rate_t_h, raw_meal_t_h), tspan, y0, options);

% Plot
figure;
subplot(2,1,1);
plot(t, y(:, 1:6:end) - 273.15); xlabel('Time (s)'); ylabel('Solid T (°C)');
title('Solid temperature vs time, all zones');
legend(arrayfun(@(i) sprintf('Zone %d', i), 1:n, 'UniformOutput', false));

subplot(2,1,2);
plot(t, y(:, 3:6:end)); xlabel('Time (s)'); ylabel('Conversion');
title('CaCO3 conversion vs time');
"""


_OCTAVE_TEMPLATE = """% {title}
% GNU Octave compatible (tested on 7.3+)
% Generated by nepal_kiln_sim v{version} on {date}
%
pkg load odepkg;
clear; clc;
n = {n_zones};
tspan = [0 {t_end_s}];

% (See kiln_ode.m for the full RHS; this is a thin driver.)
y0 = zeros(6*n, 1);
for i = 1:n
    y0(6*i-5) = {T_s0};
    y0(6*i-4) = {T_g0};
    y0(6*i-3) = {T_w0};
    y0(6*i-2) = {conv0};
    y0(6*i-1) = {co20};
    y0(6*i-0) = {o20};
end

% ode15s for stiff systems
[t, y] = ode15s(@(t,y) kiln_rhs(t, y, n), tspan, y0);
plot(t, y(:, 1:6:end) - 273.15);
xlabel('Time (s)'); ylabel('Solid T (°C)');
title('Solid temperature (5-zone kiln, Octave)');
"""


def _format_params_block(p: KilnParameters) -> str:
    lines = []
    for k, v in p.model_dump().items():
        if isinstance(v, (int, float, str, bool)):
            lines.append(f"%   {k} = {v}")
    return "\n".join(lines)


def export_matlab_script(path: str, p: KilnParameters,
                         title: str = "Rotary cement kiln simulation") -> str:
    from datetime import datetime
    body = _MATLAB_TEMPLATE.format(
        title=title,
        version="0.2.0",
        date=datetime.utcnow().strftime("%Y-%m-%d"),
        params_block=_format_params_block(p),
        n_zones=p.n_zones,
        length_m=p.length_m,
        diameter_m=p.diameter_m,
        fuel_rate_t_h=p.fuel_rate_t_h,
        raw_meal_throughput_t_h=p.raw_meal_throughput_t_h,
        t_end_s=p.t_end_s,
        T_s0=p.ambient_temp_k,
        T_g0=800.0,
        T_w0=600.0,
        conv0=p.precalciner_degree,
        co20=0.25,
        o20=0.10,
    )
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    return path


def export_octave_script(path: str, p: KilnParameters,
                         title: str = "Rotary cement kiln (Octave)") -> str:
    from datetime import datetime
    body = _OCTAVE_TEMPLATE.format(
        title=title,
        version="0.2.0",
        date=datetime.utcnow().strftime("%Y-%m-%d"),
        n_zones=p.n_zones,
        t_end_s=p.t_end_s,
        T_s0=p.ambient_temp_k,
        T_g0=800.0,
        T_w0=600.0,
        conv0=p.precalciner_degree,
        co20=0.25,
        o20=0.10,
    )
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    return path
