#!/bin/bash
# =============================================================================
# Himalayan Space Solutions — Production Deploy Script
# =============================================================================
# For: NVIDIA GPU machine ($30/hr cap, Singapore/Mumbai region preferred)
# This script does EVERYTHING in one shot:
#   1. Installs system deps
#   2. Installs Docker + NVIDIA Container Toolkit
#   3. Clones the platform from GitHub
#   4. Builds + starts all containers (API, Streamlit, Postgres, MQTT, Redis, Grafana, Prometheus)
#   5. Sets up Cloudflare tunnel for public URL (no domain needed)
#   6. Sets up backups, firewall, monitoring
#   7. Runs the pilot to verify
# Time: 5-10 minutes
# =============================================================================

set -euo pipefail

GITHUB_REPO="${GITHUB_REPO:-https://github.com/nishchalbaniya/Nepal-Industrial-Decarbonization.git}"
APP_DIR="${APP_DIR:-/opt/himalayan-space-solutions}"
DOMAIN="${DOMAIN:-himalayanspacesolutions.com.np}"
ADMIN_EMAIL="${ADMIN_EMAIL:-ops@himalayanspacesolutions.com.np}"
BRANCH="${BRANCH:-main}"

# Colors
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()  { echo -e "${RED}[ERR ]${NC} $1"; }

# Sanity
if [ "$EUID" -ne 0 ]; then
  err "Please run as root: sudo $0"
  exit 1
fi

# Detect region
info "Detecting region..."
REGION=$(curl -fsS --max-time 5 https://ipinfo.io/region 2>/dev/null || echo "unknown")
info "Region: $REGION"

# =============================================================================
# 1. System dependencies
# =============================================================================
info "Installing system dependencies..."
apt-get update -qq
apt-get install -y -qq \
    git curl wget jq nginx certbot python3-certbot-nginx \
    ufw chrony apt-transport-https ca-certificates gnupg lsb-release \
    htop net-tools unzip

# =============================================================================
# 2. Docker
# =============================================================================
if ! command -v docker &> /dev/null; then
    info "Installing Docker..."
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sh /tmp/get-docker.sh
    systemctl enable docker
    systemctl start docker
else
    info "Docker already installed: $(docker --version)"
fi

# Compose
if ! docker compose version &> /dev/null; then
    info "Installing Docker Compose plugin..."
    apt-get install -y -qq docker-compose-plugin
fi

# NVIDIA Container Toolkit (for vLLM / LLM advisor)
if command -v nvidia-smi &> /dev/null; then
    info "NVIDIA GPU detected:"
    nvidia-smi -L
    if ! dpkg -l | grep -q nvidia-container-toolkit; then
        info "Installing NVIDIA Container Toolkit..."
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | \
            sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
            sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
            sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
        apt-get update -qq
        apt-get install -y -qq nvidia-container-toolkit
        nvidia-ctk runtime configure --runtime=docker
        systemctl restart docker
        info "NVIDIA Container Toolkit installed"
    fi
else
    warn "No NVIDIA GPU detected — vLLM (LLM advisor) will not be available"
    warn "The platform will run on CPU only (still fast enough for the API)"
fi

# =============================================================================
# 3. Clone / update repo
# =============================================================================
if [ -d "$APP_DIR/.git" ]; then
    info "Updating existing repo at $APP_DIR"
    cd "$APP_DIR"
    git fetch --all
    git checkout "$BRANCH"
    git pull --rebase --autostash
else
    info "Cloning $GITHUB_REPO to $APP_DIR"
    git clone --branch "$BRANCH" "$GITHUB_REPO" "$APP_DIR"
fi

cd "$APP_DIR"

# =============================================================================
# 4. Generate secrets
# =============================================================================
DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
JWT_SECRET=$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)
MQTT_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=' | head -c 16)
GRAFANA_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=' | head -c 16)

info "Writing .env..."
cat > "$APP_DIR/.env" <<EOF
# Auto-generated by deploy_production.sh on $(date)
GITHUB_REPO=$GITHUB_REPO
BRANCH=$BRANCH
DOMAIN=$DOMAIN
ADMIN_EMAIL=$ADMIN_EMAIL
POSTGRES_PASSWORD=$DB_PASSWORD
JWT_SECRET=$JWT_SECRET
MQTT_PASSWORD=$MQTT_PASSWORD
GRAFANA_PASSWORD=$GRAFANA_PASSWORD
TZ=Asia/Kathmandu
ENVIRONMENT=production
LOG_LEVEL=INFO
# LLM advisor: set to 1 if you have a GPU and vLLM running
ENABLE_LLM_ADVISOR=0
LLM_BACKEND=stub
ALERT_WEBHOOK=
EOF
chmod 600 "$APP_DIR/.env"
mkdir -p /root/.himalayan-space-solutions
cat > /root/.himalayan-space-solutions/credentials.txt <<EOF
DOMAIN=$DOMAIN
DB_PASSWORD=$DB_PASSWORD
JWT_SECRET=$JWT_SECRET
MQTT_PASSWORD=$MQTT_PASSWORD
GRAFANA_PASSWORD=$GRAFANA_PASSWORD
EOF
chmod 600 /root/.himalayan-space-solutions/credentials.txt
info "Credentials saved to /root/.himalayan-space-solutions/credentials.txt"

# =============================================================================
# 5. Bring up the platform
# =============================================================================
info "Starting database..."
cd "$APP_DIR/pro/deploy/vps"
docker compose --env-file "$APP_DIR/.env" up -d db
info "Waiting for database to be ready..."
for i in {1..30}; do
    if docker exec nepal-decarb-db pg_isready -U nepal_admin -d nepal_decarb &> /dev/null; then
        info "Database is ready"
        break
    fi
    sleep 2
done

info "Starting full stack..."
docker compose --env-file "$APP_DIR/.env" up -d

info "Waiting for services to be healthy..."
for i in {1..30}; do
    if curl -fsS http://localhost:8000/health &> /dev/null; then
        info "FastAPI is up"
        break
    fi
    sleep 2
done
for i in {1..30}; do
    if curl -fsS http://localhost:8501/_stcore/health &> /dev/null; then
        info "Streamlit is up"
        break
    fi
    sleep 2
done

# =============================================================================
# 6. Cloudflare tunnel (public URL, no domain needed)
# =============================================================================
info "Setting up Cloudflare tunnel for public access..."
if [ ! -f /usr/local/bin/cloudflared ]; then
    wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
        -O /usr/local/bin/cloudflared
    chmod +x /usr/local/bin/cloudflared
fi

# Create systemd service for the tunnel
cat > /etc/systemd/system/hss-tunnel.service <<EOF
[Unit]
Description=Himalayan Space Solutions Cloudflare Tunnel
After=docker.service
Requires=docker.service

[Service]
Type=simple
ExecStart=/usr/local/bin/cloudflared tunnel --url http://localhost:8000 --no-autoupdate
Restart=always
RestartSec=10
StandardOutput=append:/var/log/hss-tunnel.log
StandardError=append:/var/log/hss-tunnel.log

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable hss-tunnel.service
systemctl start hss-tunnel.service

info "Waiting for tunnel to come up..."
sleep 10
TUNNEL_URL=$(grep -oE "https://[a-z-]+\.trycloudflare\.com" /var/log/hss-tunnel.log | head -1)
if [ -n "$TUNNEL_URL" ]; then
    info "Tunnel URL: $TUNNEL_URL"
    echo "$TUNNEL_URL" > /root/.himalayan-space-solutions/tunnel_url.txt
else
    warn "Tunnel URL not detected yet. Check: journalctl -u hss-tunnel"
fi

# =============================================================================
# 7. Backups
# =============================================================================
info "Setting up daily backup..."
cat > /etc/cron.daily/hss-backup <<'EOF'
#!/bin/bash
set -e
BACKUP_DIR=/var/backups/himalayan-space-solutions
mkdir -p "$BACKUP_DIR/db"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
docker exec nepal-decarb-db pg_dump -U nepal_admin -d nepal_decarb --format=custom | \
    gzip > "$BACKUP_DIR/db/db-$TIMESTAMP.dump.gz"
# Also backup the .env
cp -a /opt/himalayan-space-solutions/.env "$BACKUP_DIR/env-$TIMESTAMP"
# S3 sync (if configured)
if [ -n "${S3_BUCKET:-}" ] && command -v aws &> /dev/null; then
    aws s3 sync "$BACKUP_DIR/db/" "s3://$S3_BUCKET/db/" --storage-class GLACIER 2>/dev/null || true
fi
# Retain 30 days
find "$BACKUP_DIR/db" -name "db-*.dump.gz" -mtime +30 -delete
find "$BACKUP_DIR" -name "env-*" -mtime +30 -delete 2>/dev/null || true
echo "[$(date)] Backup complete: db-$TIMESTAMP.dump.gz" >> /var/log/hss-backup.log
EOF
chmod +x /etc/cron.daily/hss-backup
info "Daily backup installed at /etc/cron.daily/hss-backup"

# =============================================================================
# 8. Firewall
# =============================================================================
info "Configuring firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 80/tcp
ufw allow 443/tcp
# MQTT only on internal network (not public)
ufw allow from 10.0.0.0/8 to any port 1883 proto tcp comment "MQTT internal"
ufw allow from 172.16.0.0/12 to any port 1883 proto tcp comment "MQTT internal"
ufw allow from 192.168.0.0/16 to any port 1883 proto tcp comment "MQTT internal"
ufw --force enable

# =============================================================================
# 9. Monitoring
# =============================================================================
info "Prometheus + Grafana are part of the stack"
info "Grafana: http://localhost:3000 (admin / $GRAFANA_PASSWORD)"
info "Prometheus: http://localhost:9090"

# =============================================================================
# 10. Run the pilot
# =============================================================================
info "Running pilot to verify everything works..."
sleep 5
cd "$APP_DIR/pro"
docker exec nepal-decarb-api python scripts/run_pilot.py 2>&1 | tail -25 || true

# =============================================================================
# 11. Print summary
# =============================================================================
PUBLIC_IP=$(curl -fsS http://checkip.amazonaws.com 2>/dev/null || echo "<server-ip>")
info "============================================="
info " 🟢 HIMALAYAN SPACE SOLUTIONS — DEPLOYED"
info "============================================="
info " Public tunnel: ${TUNNEL_URL:-check /var/log/hss-tunnel.log}"
info " Public IP:      $PUBLIC_IP"
info " FastAPI:        http://$PUBLIC_IP:8000/docs"
info " Streamlit:      http://$PUBLIC_IP:8501"
info " Grafana:        http://$PUBLIC_IP:3000  (admin / $GRAFANA_PASSWORD)"
info " Prometheus:     http://$PUBLIC_IP:9090"
info " "
info " Credentials:   /root/.himalayan-space-solutions/credentials.txt"
info " Backup:         /var/backups/himalayan-space-solutions/"
info " "
info " First steps:"
info "   1. Open ${TUNNEL_URL:-http://localhost:8000/docs} → FastAPI Swagger"
info "   2. Open http://$PUBLIC_IP:8501 → Streamlit dashboard"
info "   3. To add a real GPU LLM advisor:"
info "      cd /opt/himalayan-space-solutions/pro/deploy/vllm"
info "      docker compose up -d"
info "      export LLM_ENDPOINT=http://localhost:8001"
info "      docker restart nepal-decarb-api"
info "============================================="
info " "
info " Next: recruit the team (see /opt/himalayan-space-solutions/team/hiring/)"
info " Next: send outreach (see /opt/himalayan-space-solutions/docs/strategy/)"
info "============================================="
