"""
Aspen Plus / Aspen HYSYS / Aspen Custom Modeler input file export.
==================================================================

We do NOT replace Aspen (that costs $20k+/yr per seat). What we do:
  1. Produce a real Aspen Plus `.inp` file with proper Fortran-stream structure
     so a process engineer can open it in Aspen and continue from there.
  2. Export HYSYS-compatible component list and feed stream specs (CSV).
  3. Export ACM-custom-modeler compatible kinetics blocks.

These files let a Nepali plant engineer who has an Aspen license start
from a validated baseline rather than building from scratch.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional


# Aspen Plus component databank names (most common cement-plant relevant)
ASPEN_COMPONENTS = {
    "AR":  "ARGON",
    "N2":  "NITROGEN",
    "O2":  "OXYGEN",
    "CO2": "CARBON-DIOXIDE",
    "CO":  "CARBON-MONOXIDE",
    "H2O": "WATER",
    "CH4": "METHANE",
    "C":   "CARBON-GRAPHITE",
    "H2":  "HYDROGEN",
    "SO2": "SULFUR-DIOXIDE",
    "NO":  "NITRIC-OXIDE",
    "NO2": "NITROGEN-DIOXIDE",
    "CaCO3":"CALCIUM-CARBONATE",
    "CaO": "CALCIUM-OXIDE",
    "Ca(OH)2":"CALCIUM-HYDROXIDE",
    "SiO2":"SILICON-DIOXIDE",
    "Al2O3":"ALUMINUM-OXIDE",
    "Fe2O3":"IRON-OXIDE",
    "MgO": "MAGNESIUM-OXIDE",
    "K2O": "POTASSIUM-OXIDE",
    "Na2O":"SODIUM-OXIDE",
    "C2S": "DICALCIUM-SILICATE",  # user-defined via ACM
    "C3S": "TRICALCIUM-SILICATE", # user-defined via ACM
    "C3A": "TRICALCIUM-ALUMINATE",# user-defined via ACM
    "C4AF":"TETRACALCIUM-ALUMINOFERRITE", # user-defined via ACM
}


@dataclass
class AspenStream:
    """A process stream for Aspen Plus input."""
    name: str
    temperature_c: float
    pressure_bar: float
    flow_kg_h: float
    composition: Dict[str, float]            # mole or mass fractions

    def to_dict(self):
        return asdict(self)


@dataclass
class AspenBlock:
    """A unit operation in Aspen Plus."""
    name: str
    block_type: str                           # RSTOIC, RYIELD, RGIBBS, COMPR, HEATX, FLASH2, FSPLIT, MIXER
    spec: Dict[str, str]                      # block-specific specs
    inlets: List[str] = field(default_factory=list)
    outlets: List[str] = field(default_factory=list)


@dataclass
class AspenKinetics:
    """Cement chemistry kinetics for ACM custom modeler."""
    component: str                            # e.g. CaCO3
    reaction: str                             # human-readable
    pre_exp: float                            # A
    activation_energy_j_mol: float            # Ea
    order_reactants: Dict[str, float] = field(default_factory=dict)
    t_range_c: tuple = (600, 1100)


class AspenExporter:
    """Generate Aspen Plus `.inp` input file from nepal_decarb_pro data.

    Usage:
        ex = AspenExporter(project="Hetauda Cement", flowsheet="CementPyro")
        ex.add_stream(AspenStream("FEED", ...))
        ex.add_block(AspenBlock("KILN", "RSTOIC", ...))
        ex.add_kinetics(AspenKinetics("CaCO3", ...))
        ex.write("hetauda.inp")
    """
    HEADER = """; Aspen Plus Input File
; Generated by nepal_decarb_pro v2.0
; Project: {project}
; Flowsheet: {flowsheet}
; DO NOT EDIT MANUALLY if you want reproducibility
; ==========================================================
"""

    COMPONENTS_SECTION = """
; COMPONENTS
COMPONENTS {components}
    {component_lines}
;

; FLOWSHEET
FLOWSHEET {flowsheet}
    BLOCK {block_ids}
;

PROPERTIES SOLIDS
    FREE-WATER H2O / COMP-LIST H2O
    SOLVENT H2O
    PROPERTY-ROUTING COMP-GROUP COMP-LIST
;

PROP-SET COMP-LIST ALL
;

DEF-STREAMS CONV ALL
;

PROP-DATA HCARBON-1
    IN-UNITS MET PRESSURE=BAR TEMPERATURE=C DELTA-T=C
    PROP-LIST SOAVE-RL / HHV MASS-VFRA / HHV-MASS ENTHALPY / DENSITY
;
"""

    STREAMS_SECTION = """
; STREAMS
{stream_definitions}
"""

    BLOCKS_SECTION = """
; BLOCKS
{block_definitions}
"""

    def __init__(self, project: str = "Nepal_Cement", flowsheet: str = "CementPyro"):
        self.project = project
        self.flowsheet = flowsheet
        self.streams: List[AspenStream] = []
        self.blocks: List[AspenBlock] = []
        self.kinetics: List[AspenKinetics] = []

    def add_stream(self, stream: AspenStream) -> None:
        self.streams.append(stream)

    def add_block(self, block: AspenBlock) -> None:
        self.blocks.append(block)

    def add_kinetics(self, kinetics: AspenKinetics) -> None:
        self.kinetics.append(kinetics)

    # --- Stream helpers ---------------------------------------------------
    @staticmethod
    def kiln_feed(name: str = "FEED", flow_kg_h: float = 200_000.0,
                  t_c: float = 80.0, p_bar: float = 1.013) -> AspenStream:
        """A typical cement kiln feed (raw mix)."""
        return AspenStream(
            name=name, temperature_c=t_c, pressure_bar=p_bar, flow_kg_h=flow_kg_h,
            composition={
                "CaCO3": 0.75, "SiO2": 0.13, "Al2O3": 0.05,
                "Fe2O3": 0.03, "MgO": 0.02, "H2O": 0.02,
            },
        )

    @staticmethod
    def coal(name: str = "COAL", flow_kg_h: float = 20_000.0,
             t_c: float = 25.0, p_bar: float = 1.013) -> AspenStream:
        """Coal feed."""
        return AspenStream(
            name=name, temperature_c=t_c, pressure_bar=p_bar, flow_kg_h=flow_kg_h,
            composition={"C": 0.65, "H2": 0.04, "O2": 0.08, "N2": 0.01, "H2O": 0.08, "ASH": 0.14},
        )

    @staticmethod
    def air(name: str = "AIR", flow_kg_h: float = 200_000.0,
            t_c: float = 25.0, p_bar: float = 1.013) -> AspenStream:
        return AspenStream(
            name=name, temperature_c=t_c, pressure_bar=p_bar, flow_kg_h=flow_kg_h,
            composition={"N2": 0.79, "O2": 0.21},
        )

    @staticmethod
    def stack(name: str = "STACK", flow_kg_h: float = 400_000.0,
              t_c: float = 200.0, p_bar: float = 1.013) -> AspenStream:
        return AspenStream(
            name=name, temperature_c=t_c, pressure_bar=p_bar, flow_kg_h=flow_kg_h,
            composition={"N2": 0.70, "O2": 0.10, "CO2": 0.18, "H2O": 0.02},
        )

    # --- Serialization ----------------------------------------------------
    def _serialize_stream(self, s: AspenStream) -> str:
        comp_lines = "\n    ".join(f"{k}  {v:.6f}" for k, v in s.composition.items())
        return f"""
STREAM {s.name}
    TEMPERATURE  = {s.temperature_c:.2f}  C
    PRESSURE     = {s.pressure_bar:.3f}  BAR
    FLOW         = {s.flow_kg_h:.2f}   KG/HR
    COMPOSITION  MASS-FRAC
        {comp_lines}
;
"""

    def _serialize_block(self, b: AspenBlock) -> str:
        spec_lines = "\n    ".join(f"{k}  {v}" for k, v in b.spec.items())
        inlet_str = " ".join(b.inlets)
        outlet_str = " ".join(b.outlets)
        return f"""
BLOCK {b.name}  {b.block_type}
    INLETS   = {inlet_str}
    OUTLETS  = {outlet_str}
    {spec_lines}
;
"""

    def _serialize_kinetics(self, k: AspenKinetics) -> str:
        react = " + ".join(f"{c}^{o}" for c, o in k.order_reactants.items())
        return f"""
; KINETICS — {k.component} : {k.reaction}
; A = {k.pre_exp:.3e}, Ea = {k.activation_energy_j_mol:.0f} J/mol
; Range: {k.t_range_c[0]}–{k.t_range_c[1]} °C
REACTION RXN_{k.component.replace('(','').replace(')','')}
    REAC-CLASS POWERLAW
    REACTANTS = {react}
    RATE-CONSTANT = {k.pre_exp:.6e}  EXP({-k.activation_energy_j_mol:.1f}/8.314/T)
;
"""

    def write(self, out_path: str) -> str:
        """Write the .inp file. Returns the path."""
        all_components = set()
        for s in self.streams:
            all_components.update(s.composition.keys())
        for k in self.kinetics:
            all_components.add(k.component)
        comp_lines = "\n    ".join(f"{c}  {ASPEN_COMPONENTS.get(c, c)}" for c in sorted(all_components))
        stream_defs = "\n".join(self._serialize_stream(s) for s in self.streams)
        block_defs = "\n".join(self._serialize_block(b) for b in self.blocks)
        kinetics_defs = "\n".join(self._serialize_kinetics(k) for k in self.kinetics)

        # Build blocks section header
        if self.blocks:
            block_ids = " ".join(b.name for b in self.blocks)
        else:
            block_ids = "KILN"

        body = self.HEADER.format(project=self.project, flowsheet=self.flowsheet)
        body += self.COMPONENTS_SECTION.format(
            components=len(all_components),
            component_lines=comp_lines,
            flowsheet=self.flowsheet,
            block_ids=block_ids,
        )
        body += self.STREAMS_SECTION.format(stream_definitions=stream_defs)
        if self.blocks:
            body += self.BLOCKS_SECTION.format(block_definitions=block_defs)
        body += "\n; KINETICS\n" + kinetics_defs
        body += "\n; END OF FILE\n"

        out = Path(out_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(body)
        return str(out)

    # --- Convenience: full cement plant ----------------------------------
    def build_cement_plant_default(self) -> None:
        """Add streams + blocks for a typical 5000 TPD cement plant."""
        self.add_stream(self.kiln_feed(flow_kg_h=208_000))
        self.add_stream(self.coal(flow_kg_h=21_000))
        self.add_stream(self.air(flow_kg_h=180_000))
        self.add_stream(self.stack(flow_kg_h=380_000))

        self.add_block(AspenBlock("PREHEAT", "HEATX",
                                   spec={"HOT-IN": "STACK", "COLD-IN": "FEED", "MIN-DT": "20"},
                                   inlets=["STACK", "FEED"], outlets=["STACK-OUT", "FEED-HOT"]))
        self.add_block(AspenBlock("CALCINER", "RSTOIC",
                                   spec={"STOIC-1": "CaCO3 -> CaO + CO2", "CONV-1": "0.95"},
                                   inlets=["FEED-HOT"], outlets=["CALCINED"]))
        self.add_block(AspenBlock("KILN", "RYIELD",
                                   spec={"TEMP": "1450", "YIELD": "BASIS"},
                                   inlets=["CALCINED", "COAL", "AIR"], outlets=["CLINKER", "FLUEGAS"]))
        self.add_block(AspenBlock("COOLER", "HEATX",
                                   spec={"HOT-IN": "CLINKER", "COLD-IN": "AIR", "MIN-DT": "50"},
                                   inlets=["CLINKER", "AIR"], outlets=["CLINKER-COLD", "AIR-HOT"]))
        self.add_block(AspenBlock("BAGHOUSE", "FSPLIT",
                                   spec={"FRAC": "0.99"},
                                   inlets=["FLUEGAS"], outlets=["STACK", "DUST"]))

        # Real cement chemistry kinetics (after Hills 1967, Bhatty 2004)
        self.add_kinetics(AspenKinetics(
            "CaCO3", "calcination",
            pre_exp=1.20e8, activation_energy_j_mol=128_500,
            order_reactants={"CaCO3": 1.0},
            t_range_c=(600, 950),
        ))
        self.add_kinetics(AspenKinetics(
            "C2S", "C2S + CaO -> C3S", pre_exp=4.50e6, activation_energy_j_mol=85_000,
            order_reactants={"C2S": 1.0, "CaO": 1.0}, t_range_c=(1200, 1500),
        ))
        self.add_kinetics(AspenKinetics(
            "C3A", "aluminate formation", pre_exp=1.00e5, activation_energy_j_mol=72_000,
            order_reactants={"CaO": 1.0, "Al2O3": 1.0}, t_range_c=(1100, 1400),
        ))


# ---------------------------------------------------------------------------
# HYSYS-compatible CSV export
# ---------------------------------------------------------------------------
class HysysExporter:
    """Export HYSYS-compatible feed stream definitions (CSV)."""
    @staticmethod
    def write_csv(streams: List[AspenStream], out_path: str) -> str:
        import csv
        out = Path(out_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with out.open("w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["Stream", "T_C", "P_bar", "Flow_kg_h",
                        "Comp1", "Frac1", "Comp2", "Frac2",
                        "Comp3", "Frac3", "Comp4", "Frac4"])
            for s in streams:
                comps = list(s.composition.items())[:4]
                row = [s.name, s.temperature_c, s.pressure_bar, s.flow_kg_h]
                for c, fr in comps:
                    row += [c, fr]
                while len(row) < 12:
                    row += ["", ""]
                w.writerow(row)
        return str(out)
