"""
MATLAB / Octave export of nepal_decarb_pro models.
==================================================

Generates .m scripts that engineers with a MATLAB license can use
to extend or cross-validate the calculations.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List


@dataclass
class MatlabExporter:
    """Generate MATLAB .m files from nepal_decarb_pro results."""

    @staticmethod
    def write_emissions_fn(out_path: str) -> str:
        code = """% nepal_decarb_emissions.m
% Generated by nepal_decarb_pro v2.0
% Tier 2 cement emissions calculation
% Reference: IPCC 2006 Vol.3 Ch.2 + Nepal-specific EFs
%
% Usage:
%   EF = nepal_decarb_emissions();
%   result = calc_tier2(EF, plant);
function EF = nepal_decarb_emissions()
    EF.clinker_process_CO2 = 0.527;     % t CO2/t clinker (IPCC)
    EF.CaO_frac_clinker    = 0.65;
    EF.MgO_frac_clinker    = 0.015;
    EF.CO2_per_t_CaO       = 0.7857;    % stoichiometric
    EF.CO2_per_t_MgO       = 1.092;
    EF.grid_EF_NP          = 0.0256;    % kg CO2/kWh (NEA 2023/24)
    EF.fuels = struct( ...
        'coal_bituminous_NP', struct('ncvc_gj_per_t', 25.5, 'ef_kgco2_per_gj', 94.6, 'price_usd_per_t', 145), ...
        'coal_anthracite_NP',  struct('ncvc_gj_per_t', 27.0, 'ef_kgco2_per_gj', 98.3, 'price_usd_per_t', 165), ...
        'petcoke',             struct('ncvc_gj_per_t', 32.0, 'ef_kgco2_per_gj', 102.0, 'price_usd_per_t', 195), ...
        'natural_gas',         struct('ncvc_gj_per_t', 50.0, 'ef_kgco2_per_gj', 56.1,  'price_usd_per_t', 380), ...
        'biomass_sawdust',     struct('ncvc_gj_per_t', 14.5, 'ef_kgco2_per_gj', 0.0,   'price_usd_per_t', 75) ...
    );
end

function result = calc_tier2(EF, plant)
    % plant: struct with clinker_t, cement_t, fuels (cell), electricity_kwh, cao_frac, mgo_frac
    %
    % Returns: struct with scope1, scope2, total, intensity_kg_per_t_cement, sec_mj_per_t_clinker
    %
    % Scope 1: process + combustion
    % Scope 2: electricity
    fuel_term  = 0;
    for i = 1:length(plant.fuels)
        f = plant.fuels{i};
        fc = EF.fuels.(f.name);
        fuel_term = fuel_term + f.consumption_t * fc.ncvc_gj_per_t * fc.ef_kgco2_per_gj / 1000;
    end
    process = plant.clinker_t * EF.clinker_process_CO2 + ...
              plant.clinker_t * (EF.CaO_frac_clinker * EF.CO2_per_t_CaO + ...
                                 EF.MgO_frac_clinker * EF.CO2_per_t_MgO);
    scope1 = process + fuel_term;
    scope2 = plant.electricity_kwh * EF.grid_EF_NP / 1000;
    result.scope1 = scope1;
    result.scope2 = scope2;
    result.total  = scope1 + scope2;
    result.intensity_kg_per_t_cement = result.total * 1000 / plant.cement_t;
    result.sec_mj_per_t_clinker = 0;  % fill from simulation
end

% Example:
% EF = nepal_decarb_emissions();
% plant.clinker_t = 950000;
% plant.cement_t  = 1100000;
% plant.electricity_kwh = 85000000;
% plant.fuels = { struct('name','coal_bituminous_NP','consumption_t',120000), ...
%                 struct('name','petcoke','consumption_t',18000) };
% result = calc_tier2(EF, plant);
% fprintf('Total: %.0f tCO2/yr, Intensity: %.0f kg/t\\n', result.total, result.intensity_kg_per_t_cement);
"""
        Path(out_path).parent.mkdir(parents=True, exist_ok=True)
        Path(out_path).write_text(code)
        return out_path

    @staticmethod
    def write_monte_carlo_fn(out_path: str) -> str:
        code = """% nepal_decarb_montecarlo.m
% Monte Carlo uncertainty quantification for cement emissions
% Usage:
%   result = montecarlo_cement(n_samples, base_emissions_tco2)
function result = montecarlo_cement(n_samples, base_emissions_tco2)
    rng(42);  % reproducibility
    % Emission factors uncertainties (GCCA, IPCC defaults)
    coal_ef_mu = 94.6;   coal_ef_sd = 3.5;   % kg/GJ
    grid_ef_mu = 0.0256; grid_ef_sd = 0.005; % kg/kWh
    clinker_ef_mu = 0.527; clinker_ef_sd = 0.025; % t/t
    % Sample
    coal_ef = normrnd(coal_ef_mu, coal_ef_sd, n_samples, 1);
    grid_ef = normrnd(grid_ef_mu, grid_ef_sd, n_samples, 1);
    clk_ef  = normrnd(clinker_ef_mu, clinker_ef_sd, n_samples, 1);
    % Use a fixed energy input (replace with plant data)
    fuel_gj = 120000 * 25.5;       % t coal * GJ/t
    electricity_kwh = 85e6;
    clinker_t = 950000;
    process = clk_ef .* clinker_t;
    combustion = coal_ef .* fuel_gj / 1000;
    scope2 = grid_ef .* electricity_kwh / 1000;
    samples = process + combustion + scope2;
    result.samples = samples;
    result.mean = mean(samples);
    result.std  = std(samples);
    result.ci_90 = prctile(samples, [5 95]);
    result.cov   = std(samples) / mean(samples);
    fprintf('Mean: %.0f tCO2, 90%% CI [%.0f, %.0f], CoV %.1f%%\\n', ...
            result.mean, result.ci_90(1), result.ci_90(2), result.cov*100);
end
"""
        Path(out_path).parent.mkdir(parents=True, exist_ok=True)
        Path(out_path).write_text(code)
        return out_path

    @staticmethod
    def write_optimization_fn(out_path: str) -> str:
        code = """% nepal_decarb_fuel_blend.m
% MILP fuel blend optimization (uses MATLAB Optimization Toolbox)
% Minimize:  w_c * cost + w_e * emissions
% Subject to: total energy = E_target
%             0 <= x_fuel <= 1
%             sum(x) = 1
%
% Usage:
%   x = nepal_decarb_fuel_blend(target_gj, w_cost, w_emission)
function x = nepal_decarb_fuel_blend(target_gj, w_cost, w_emission)
    if nargin < 2, w_cost = 0.5; w_emission = 0.5; end
    % Fuel data: name, NCV (GJ/t), EF (kg/GJ), price (USD/t)
    fuels = {'coal_bituminous_NP', 25.5, 94.6, 145; ...
             'petcoke',            32.0, 102.0, 195; ...
             'natural_gas',        50.0, 56.1, 380; ...
             'biomass_sawdust',    14.5, 0.0, 75; ...
             'rdf_municipal',      10.0, 21.0, 35};
    n = size(fuels,1);
    % Cost per GJ, emissions per GJ
    cost_per_gj = zeros(n,1);
    em_per_gj   = zeros(n,1);
    for i = 1:n
        cost_per_gj(i) = fuels{i,4} / fuels{i,2};
        em_per_gj(i)   = fuels{i,3};
    end
    % Minimize:  w_c * cost_per_gj' * x + w_e * em_per_gj' * x
    f = w_cost * cost_per_gj + w_emission * em_per_gj;
    Aeq = ones(1,n); beq = 1;  % blend fractions sum to 1
    lb = zeros(n,1); ub = ones(n,1);
    A = []; b = [];
    x = linprog(f, A, b, Aeq, beq, lb, ub);
    if isempty(x), error('LP infeasible'); end
    % Report
    fprintf('Optimal blend:\\n');
    for i = 1:n
        if x(i) > 0.001
            fprintf('  %-25s  %5.1f%%\\n', fuels{i,1}, x(i)*100);
        end
    end
    total_cost   = x' * cost_per_gj * target_gj;
    total_em     = x' * em_per_gj   * target_gj / 1000;
    fprintf('Total cost: $%.0f  Emissions: %.0f tCO2\\n', total_cost, total_em);
end
"""
        Path(out_path).parent.mkdir(parents=True, exist_ok=True)
        Path(out_path).write_text(code)
        return out_path
