% kiln_rhs.m — Right-hand side for the 5-zone rotary cement kiln ODE.
%
% Companion to nepal_kiln_sim (Python). 5-zone model:
%   1. Drying       2. Preheating  3. Calcination
%   4. Burning      5. Cooling
%
% State y is laid out per zone (6 vars each):
%   y(6i-5) = T_solid  (K)
%   y(6i-4) = T_gas    (K)
%   y(6i-3) = T_wall   (K)
%   y(6i-2) = conversion (0-1)
%   y(6i-1) = CO2      (mass fraction)
%   y(6i-0) = O2       (mass fraction)
%
% Run with:  ode15s(@(t,y) kiln_rhs(t,y, p), tspan, y0, options)
%
% Parameters struct p is required to have (at minimum):
%   p.n_zones, p.length_m, p.diameter_m, p.fuel_rate_t_h,
%   p.raw_meal_throughput_t_h, p.fuel_ncvc_gj_per_t, p.fuel_ef_kgco2_per_gj,
%   p.ambient_temp_k, p.rotation_rpm, p.slope_deg,
%   p.arrhenius_a, p.arrhenius_ea_j_per_mol, p.dH_calcination_j_per_kg,
%   p.cp_solid, p.cp_gas, p.emissivity, p.wall_loss_coeff_w_m2_k
%
% Generated by nepal_kiln_sim. See ../src/nepal_kiln_sim/kiln_ode.py for the
% reference Python implementation.

function dydt = kiln_rhs(t, y, p)
    R = 8.314;
    sigma = 5.670374419e-8;
    n = p.n_zones;

    % Unpack state
    T_s = y(1:6:end);  T_s = max(p.ambient_temp_k, min(T_s, 2000));
    T_g = y(2:6:end);  T_g = max(p.ambient_temp_k, min(T_g, 2500));
    T_w = y(3:6:end);  T_w = max(p.ambient_temp_k, min(T_w, 1500));
    conv = max(0, min(1, y(4:6:end)));
    co2  = max(0, min(0.5, y(5:6:end)));
    o2   = max(0, min(0.25, y(6:6:end)));

    % Geometry
    A_cross = pi * (p.diameter_m / 2)^2;
    perim   = pi * p.diameter_m;

    % Flows
    solid_flow_kg_s = p.raw_meal_throughput_t_h * 1000 / 3600;
    air_kg_s        = p.fuel_rate_t_h * 1000 / 3600 * 8.5;
    fuel_kg_s       = p.fuel_rate_t_h * 1000 / 3600;
    co2_comb_kg_s   = fuel_kg_s * p.fuel_ncvc_gj_per_t * p.fuel_ef_kgco2_per_gj / 1000;
    co2_calc_kg_s   = solid_flow_kg_s * 0.65 * 0.7857;
    gas_flow_kg_s   = air_kg_s + fuel_kg_s + co2_comb_kg_s + co2_calc_kg_s;

    % Solid hold-up
    axial_v = max((p.rotation_rpm / 60) * p.diameter_m * tan(p.slope_deg * pi / 180) * 0.5, 0.01);
    residence = p.length_m / axial_v;
    solid_per_m = (solid_flow_kg_s * residence) / max(p.length_m, 1e-3);

    % Heat transfer
    Re = 0.6 * (gas_flow_kg_s / max(0.6 * A_cross, 1e-6)) * p.diameter_m / 4e-5;
    h_conv = max(1, 0.023 * Re^0.8 * 0.7^0.4 * 0.05 / p.diameter_m);

    % Wall (quasi-steady)
    q_loss = p.wall_loss_coeff_w_m2_k * (T_w - p.ambient_temp_k) * perim;
    rhs_w  = 0.5 * (T_g.^4 + T_s.^4) + q_loss / max(p.emissivity * sigma * perim, 1e-9);
    T_w_new = max(p.ambient_temp_k, rhs_w.^(0.25));

    % Reaction (CaCO3 -> CaO + CO2)
    r_react = zeros(n, 1);
    for i = 1:n
        if T_s(i) > 700
            k_react = p.arrhenius_a * exp(-p.arrhenius_ea_j_per_mol / (R * T_s(i)));
            r_react(i) = min(k_react * (1 - conv(i)) * solid_per_m, 0.5 * solid_per_m);
        end
    end

    % Combustion heat (W)
    Q_total = fuel_kg_s * p.fuel_ncvc_gj_per_t * 1e6;
    q_comb = zeros(n, 1);
    if n >= 2
        q_comb(end)   = 0.75 * Q_total;
        q_comb(end-1) = 0.20 * Q_total;
        if n >= 3, q_comb(end-2) = 0.05 * Q_total; end
    else
        q_comb(end) = Q_total;
    end

    % Energy balances
    dT_s = zeros(n, 1);
    dT_g = zeros(n, 1);
    for i = 1:n
        q_conv_s = h_conv * A_cross * (T_g(i) - T_s(i)) / max(solid_per_m, 1e-3);
        q_rad_s  = p.emissivity * sigma * A_cross * (T_w_new(i)^4 - T_s(i)^4) / max(solid_per_m, 1e-3);
        dT_s(i) = (q_conv_s + q_rad_s - r_react(i) * p.dH_calcination_j_per_kg / max(solid_per_m, 1e-3)) / p.cp_solid;

        q_conv_g = h_conv * A_cross * (T_s(i) - T_g(i)) / max(gas_flow_kg_s / n, 1e-3);
        dT_g(i) = (q_conv_g + q_comb(i) / max(gas_flow_kg_s / n, 1e-3)) / p.cp_gas;
        if T_g(i) > 2300, dT_g(i) = min(dT_g(i), 0); end
    end

    % Mass balances
    dconv = r_react / max(solid_per_m, 1e-3);
    dco2  = r_react * 0.44 / max(gas_flow_kg_s / n, 1e-3);

    o2_cons = fuel_kg_s * 2.5;
    do2 = zeros(n, 1);
    if n >= 3
        do2(end)   = -0.75 * o2_cons / max(gas_flow_kg_s / n, 1e-3);
        do2(end-1) = -0.20 * o2_cons / max(gas_flow_kg_s / n, 1e-3);
        do2(end-2) = -0.05 * o2_cons / max(gas_flow_kg_s / n, 1e-3);
    else
        do2(end) = -o2_cons / max(gas_flow_kg_s / n, 1e-3);
    end

    % Repack
    dydt = zeros(size(y));
    dydt(1:6:end) = dT_s;
    dydt(2:6:end) = dT_g;
    dydt(3:6:end) = (T_w_new - T_w) / 30;     % 30-s wall lag
    dydt(4:6:end) = dconv;
    dydt(5:6:end) = dco2;
    dydt(6:6:end) = do2;
end
