"""
I/O for cooler simulation results.

Mirrors the structure of nepal_kiln_sim/io.py for consistency.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np

from .cooler_ode import CoolerParameters, CoolerState


def save_results_csv(path: str, t: np.ndarray, y: np.ndarray, x: np.ndarray,
                     p: CoolerParameters) -> str:
    n = p.n_cells
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write("time_s,x_m,T_clinker_C,T_air_C\n")
        # For the quasi-steady cooler, y is (2*n, 1); for time-trajectories,
        # y is (2*n, n_time). Handle both.
        if y.ndim == 2 and y.shape[1] == 1:
            ti = 0
            for zi in range(n):
                f.write(f"{float(t[ti]):.4f},{x[zi]:.4f},{float(y[zi, ti]):.4f},{float(y[n + zi, ti]):.4f}\n")
        else:
            for ti in range(y.shape[1]):
                for zi in range(n):
                    f.write(f"{float(t[ti]):.4f},{x[zi]:.4f},{float(y[zi, ti]):.4f},{float(y[n + zi, ti]):.4f}\n")
    return path


def load_results_csv(path: str) -> dict:
    import csv
    cols = {}
    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            for k, v in row.items():
                cols.setdefault(k, []).append(float(v))
    return {k: np.array(v) for k, v in cols.items()}


def save_results_json(path: str, state: CoolerState, p: CoolerParameters,
                      outputs: dict) -> str:
    payload = {
        "tool": "nepal_cooler_sim",
        "version": "0.3.0",
        "parameters": json.loads(p.model_dump_json()),
        "state_summary": state.summary(),
        "outputs": outputs,
    }
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, default=_json_default)
    return path


def _json_default(o: Any) -> Any:
    if isinstance(o, np.ndarray):
        return o.tolist()
    if isinstance(o, (np.floating,)):
        return float(o)
    if isinstance(o, (np.integer,)):
        return int(o)
    if isinstance(o, (np.bool_,)):
        return bool(o)
    return str(o)


# --- MATLAB / Octave export ------------------------------------------------

_MATLAB_TEMPLATE = """% {title}
% Generated by nepal_cooler_sim v{version} on {date}
% 1D cross-flow grate cooler (cement clinker)
% Run with MATLAB R2020b+ or GNU Octave 7+

clear; clc;
n = {n_cells};
L = {length_m};
W = {width_m};
h_bed = {bed_depth_m};
v_grate = {grate_speed_m_min} / 60;       % m/s
T_in = {clinker_inlet_t_c};                % C
T_out_target = {clinker_outlet_t_c};       % C
v_air = {under_grate_air_velocity_m_s};    % m/s
T_air_in = {under_grate_air_temp_c};
m_clinker_t_h = {clinker_throughput_t_h};
rho_bulk = {rho_clinker_kg_m3};
cp_clinker = {cp_clinker_kj_kg_k} * 1000;  % J/(kg K)
emiss = {emissivity};

m_clinker = m_clinker_t_h * 1000 / 3600;
y0 = zeros(2 * n, 1);
for i = 1:n
    y0(i) = T_in;
    y0(n + i) = T_air_in;
end

tspan = [0 {t_end_s}];
options = odeset('RelTol', 1e-5, 'AbsTol', 1e-7, 'MaxStep', 5);
[t, y] = ode15s(@(t,y) cooler_rhs(t, y, n, L, W, h_bed, v_grate, v_air, ...
    m_clinker, rho_bulk, cp_clinker, emiss), tspan, y0, options);

% Final spatial profile
T_clinker = y(end, 1:n);
T_air = y(end, n+1:end);
x = linspace(0, L, n);

figure;
subplot(2,1,1);
plot(x, T_clinker); xlabel('Grate position (m)'); ylabel('Clinker T (C)');
title('Clinker temperature along grate (steady state)');

subplot(2,1,2);
plot(x, T_air); xlabel('Grate position (m)'); ylabel('Cooling air T (C)');
title('Cooling air temperature along grate');

fprintf('Clinker outlet: %.1f C (target %.1f C)\\n', T_clinker(end), T_out_target);
"""


def export_matlab_script(path: str, p: CoolerParameters,
                         title: str = "Grate cooler simulation") -> str:
    body = _MATLAB_TEMPLATE.format(
        title=title,
        version="0.3.0",
        date=datetime.now().strftime("%Y-%m-%d"),
        n_cells=p.n_cells,
        length_m=p.length_m,
        width_m=p.width_m,
        bed_depth_m=p.bed_depth_m,
        grate_speed_m_min=p.grate_speed_m_min,
        clinker_inlet_t_c=p.clinker_inlet_t_c,
        clinker_outlet_t_c=p.clinker_outlet_t_c,
        under_grate_air_velocity_m_s=p.under_grate_air_velocity_m_s,
        under_grate_air_temp_c=p.under_grate_air_temp_c,
        clinker_throughput_t_h=p.clinker_throughput_t_h,
        rho_clinker_kg_m3=p.rho_clinker_kg_m3,
        cp_clinker_kj_kg_k=p.cp_clinker_kj_kg_k,
        emissivity=p.emissivity,
        t_end_s=p.t_end_s,
    )
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    return path


def export_octave_script(path: str, p: CoolerParameters,
                         title: str = "Grate cooler (Octave)") -> str:
    # Octave uses the same script with odepkg
    body = export_matlab_script(path, p, title)  # Octave can run MATLAB code
    text = Path(path).read_text(encoding="utf-8")
    text = text.replace("clear; clc;", "pkg load odepkg;\nclear; clc;")
    Path(path).write_text(text, encoding="utf-8")
    return path
